<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Растягиваемый фон</title>
    <style>
        body {
            background: url(https://i.ibb.co/pLZ7ps8/vlv.jpg) no-repeat;
            -moz-background-size: 100%; /* Firefox 3.6+ */
            -webkit-background-size: 100%; /* Safari 3.1+ и Chrome 4.0+ */
            -o-background-size: 100%; /* Opera 9.6+ */
            background-size: 100%; /* Современные браузеры */
        }
    </style>
</head>
<body>
</body>
</html>

